### ISSUE TITLE
Error on clicking on Excel Sheet when script is running in background

### ISSUE THREAD

**Issue by Ashish424** [ZoomerAnalytics/xlwings#797] opened 2018-01-07 18:16 UTC
I am using Windows 10 python 3.6.2 and Excel 2016.
I wrote a basic python script which updates a cell regularly in background.
```
import xlwings as xw
import time
import random
book = xw.Book("pybook.xlsm")
sht = book.sheets['Sheet1']
print(sht.range(1, 1).value)

while True:
    val = random.randint(0, 9)
    sht.range('A1').options(numbers=int).value = val
    time.sleep(0.1)``
```
The script works fine but as soon as I click on any cell in excel(just clicking not updating) the script crashes with the following error.

```
Traceback (most recent call last):
  File "C:/Users/ashis/Desktop/PythonExcel/test.py", line 10, in <module>
    sht.range('A1').options(numbers=int).value = val
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\xlwings\main.py", line 1495, in value
    conversion.write(data, self, self._options)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\xlwings\conversion\__init__.py", line 35, in write
    pipeline(ctx)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\xlwings\conversion\framework.py", line 66, in __call__
    stage(*args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\xlwings\conversion\standard.py", line 91, in __call__
    self._write_value(ctx.range, ctx.value, scalar)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\xlwings\conversion\standard.py", line 71, in _write_value
    rng.raw_value = value
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\xlwings\main.py", line 1116, in raw_value
    self.impl.raw_value = data
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\xlwings\_xlwindows.py", line 709, in raw_value
    self.xl.Value = data
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\xlwings\_xlwindows.py", line 98, in __setattr__
    return setattr(self._inner, key, value)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\win32com\client\dynamic.py", line 565, in __setattr__
    self._oleobj_.Invoke(entry.dispid, 0, invoke_type, 0, value)
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2146777998), None)
```

**Comment by fzumstein** [comment] 2018-01-07 18:44
duplicate of #587

**Closed by fzumstein** 2018-01-07 18:44 UTC
