### ISSUE TITLE
@xw.ret(dict) fails for key,val pair when len(val)>255 characters

### ISSUE THREAD

**Issue by yugmorf** [ZoomerAnalytics/xlwings#869] opened 2018-05-11 02:59 UTC
Hello,

One of my python dictionary imports using xlwings udf failed (all cells filled with '#VALUE!') and I traced the cause to the string length of one of the dictionary entries which exceeded 255 characters.  It seems that both excel (cells) and VBA strings can hold longer strings than this, so not sure where the limit is getting enforced.

I'm new to xlwings and to python.  Thank you for your work in producing this fabulous product.

Best regards,
Yug

**Comment by fzumstein** [comment] 2018-05-11 07:44
Looks like a duplicate of #456

**Closed by fzumstein** 2018-05-11 07:44 UTC
