### ISSUE TITLE
Run-time error '9' Subscript out of range with sheet xlwings.conf added after workbook creation

### ISSUE THREAD

**Issue by ilrico** [ZoomerAnalytics/xlwings#708] opened 2017-07-11 15:29 UTC
I created a new sheet then renamed it to "xlwings.conf" (in VBA editor properties it appears with (name) set to Sheet6 and name set to xlwings.conf
Then if I try click on addin "Restart UDFs server" or "Import functions" I have the error Subscript out of range on line(in function GetConfigFromSheet() ):
Set sht = ThisWorkbook.Sheets("xlwings.conf")

**Comment by fzumstein** [comment] 2017-07-11 22:07
what's the content of your xlwings.conf sheet?

**Comment by ilrico** [comment] 2017-07-12 06:57
Exactly the exemple found on https://github.com/ZoomerAnalytics/xlwings/blob/master/docs/addin.rst
Keys on column A and values on B, 6 lines. Same keys/values.

**Comment by fzumstein** [comment] 2017-07-12 13:11
please try with a spreadsheet produced by `xlwings quickstart` command line

**Comment by andreicrisan11** [comment] 2017-07-13 12:41
I have the same issue as @ilrico  even though I installed it via xlwings quickstart. Any idea as to what the problem might be? 

At first I had the "xlwings32.dll not found" error however after changing the name of the last sheet from "_xlwings.conf" to "xlwings.conf" (as instructed in the sheet) the error switched to this one. 

xlwings.conf sheet is the same as the default one. Been struggling for the past two days to make this work, and have no idea what else there is to do. 

Would really appreciate a fix, as it seems like an amazing tool, and I want to do all the statistics and data manipulation even from the database in python as opposed to VBA.

**Comment by fzumstein** [comment] 2017-07-13 16:16
Can somebody please upload s workbook that produces that error? thanks

**Comment by andreicrisan11** [comment] 2017-07-13 21:57
[Rate_hike_probability.zip](https://github.com/ZoomerAnalytics/xlwings/files/1146772/Rate_hike_probability.zip)

These are the ones, they are just the templates created directly from calling the command xlwings quickstart.

**Comment by fzumstein** [comment] 2017-07-13 21:59
thx I found the issue in the meantime, will release a fix tomorrow

Am 13.07.2017 11:57 nachm. schrieb "andreicrisan11" <
notifications@github.com>:

**Comment by andreicrisan11** [comment] 2017-07-14 07:20
Perfect, thank you. Would you please be able to let us know when the fix has been released so that we can try it out?

**Closed** 2017-07-14 17:18 UTC
Labels: bug

**Comment by fzumstein** [comment] 2017-07-14 18:44
please try with 0.11.3, make sure to update the addin.

**Comment by andreicrisan11** [comment] 2017-07-18 10:11
How do i update it? i saw that updating the add in is done simply by typing in the command `xlwings addin update`, but how do i get the version you mentioned?

**Comment by ilrico** [comment] 2017-07-18 10:16
Have you tried via pip ?

**Comment by andreicrisan11** [comment] 2017-07-18 10:26
Apologies for the dumb question above. So I have upgraded to 0.11.3 and I have updated the addin as well. However, the error I get now is the xlwings.dll file not found one.

**Comment by fzumstein** [comment] 2017-07-18 21:39
Please follow the troubleshooting here (will be part of the docs with the next release): https://github.com/ZoomerAnalytics/xlwings/blob/master/docs/troubleshooting.rst

**Comment by andreicrisan11** [comment] 2017-07-19 13:30
Thank you!! It finally works!!

**Comment by theodormunteanu** [comment] 2017-07-22 01:52
The problem persists in my case.
I use Spyder (part from Anaconda 3) but I put as interpreter the pythonw.exe file from  user\...\anaconda file.
See here the 4 files: the source, the worksheet and the vba debug line + error
![err1_vba](https://user-images.githubusercontent.com/30360957/28487466-c6689d44-6e88-11e7-85a4-4639a7b7b94f.jpg)
![err2_vba](https://user-images.githubusercontent.com/30360957/28487467-c66b2438-6e88-11e7-99c5-b8cd92fc5681.jpg)
![source](https://user-images.githubusercontent.com/30360957/28487468-c66c506a-6e88-11e7-9b64-63c3e0ea1429.jpg)
![worksheet](https://user-images.githubusercontent.com/30360957/28487469-c66c5c9a-6e88-11e7-9abd-654738006e59.jpg)



.

**Comment by theodormunteanu** [comment] 2017-07-22 02:24
In fact, after closing and restarting excel, it's even worse, it seems I am back to square 1.
I have to reattach in VBA and EXCEL the new add-in but it seems it gives me the old repository.(and also there are several workbooks with the same name in VBA which causes me an alert at the start of the program).If before I managed to eliminate the password,now it's all messed up.
In my opinion, a tutorial on how to install from the beginning to the end UDF ' s in EXCEL and VBA wouldn't hurt, because even though there are some answers on the web on how to do some steps, there are way too overdispersed and I don't have time to research an entire week-end for this.

**Comment by ilrico** [comment] 2017-07-24 07:28
@theodormunteanu, in your screenshots there is no spreadsheet named "xlwings.conf" so no wonder it does not find it.

**Comment by theodormunteanu** [comment] 2017-07-24 08:45
In the mean time I changed the laptop and installed normally on office 365 2016 and it's working perfectly.
However, I insist on the idea of making a step-by-step tutorial on how to install. Not just the main steps, but with all details. The installation is a pain in the ass.

**Comment by fzumstein** [comment] 2017-07-24 21:33
The issue is really just the add-in (your screenshot shows still the old version which is why it failed). Anyhow, there's an issue for that: https://github.com/ZoomerAnalytics/xlwings/issues/704 please continue on #704 if you have more inputs.
