### ISSUE TITLE
Accept datetime.timedelta as valid time type

### ISSUE THREAD

**Issue by Juanlu001** [ZoomerAnalytics/xlwings#492] opened 2016-06-16 13:43 UTC
xlwings 0.6.4, Python 2.7, Windows

The class `datetime.timedelta` results of subtracting two times:

https://docs.python.org/2/library/datetime.html#available-types

For instance:

``` python
>>> import datetime as dt
>>> delta = dt.datetime.now() - dt.datetime(2016, 6, 16)
>>> delta
datetime.timedelta(0, 56230, 915000)
```

The problem is that xlwings does not recognize this time as a valid time type:

https://github.com/ZoomerAnalytics/xlwings/blob/v0.6.4/xlwings/main.py#L880
https://github.com/ZoomerAnalytics/xlwings/blob/v0.6.4/xlwings/_xlwindows.py#L40

so when setting a cell value to a `datetime.timedelta` object, it goes to https://github.com/ZoomerAnalytics/xlwings/blob/v0.6.4/xlwings/main.py#L896 and fails. I cannot test this with 0.7.x right now, so perhaps this is already fixed.

cc @skasi7

**Comment by denfromufa** [comment] 2016-06-16 13:57
@Juanlu001 is there timedelta type in Excel cells?

**Comment by fzumstein** [comment] 2016-06-16 14:12
What do you do with 

```
>>> delta = dt.datetime.now() - dt.datetime(2015, 6, 16)
>>> delta
datetime.timedelta(366, 58092, 285807)
```

**Comment by Juanlu001** [comment] 2016-06-16 14:15
Right now I'm extracting the `.total_seconds()`, dividing by 3600 to convert to hours and pass it to the cell.

**Comment by fzumstein** [comment] 2016-06-16 14:18
Fair enough but then this is really about time and as such a duplicate of https://github.com/ZoomerAnalytics/xlwings/issues/86 and not about timedelta.

**Comment by fzumstein** [comment] 2017-01-14 19:12
closing this as it's a duplicated as mentioned. feel free to reopen if you think differently.

**Closed by fzumstein** 2017-01-14 19:12 UTC

**Comment by evan54** [comment] 2021-05-20 19:33
I wrote a slightly modified converter which I'd argue could be included in the default Pandas converter (or some similar functionality).

```
class DataFrame(Converter):

    base = PandasDataFrameConverter

    @staticmethod
    def read_value(df, options):
        return df

    @staticmethod
    def write_value(df, options):
        tdy = pd.Timestamp('now').normalize()
        for col, dtype in df.dtypes.items():
            if is_timedelta64_dtype(dtype):
                # could do something smarter here where
                # if it's less than 1 day and positive
                # then can return smth like
                # df[col] = (tdy + df[col]).strftime('%H:%M:%S')                                     
                df[col] = df[col].total_seconds() / 60 / 60 / 24
        return df

    @staticmethod
    def read_value(df, options):
        return df
```

**Comment by fzumstein** [comment] 2022-08-13 08:38
This has been revived in https://github.com/xlwings/xlwings/issues/492

**Comment by astrojuanlu** [comment] 2022-08-13 10:12
I guess you mean gh-1991?

(Wow, time flies 😁)

**Comment by fzumstein** [comment] 2022-08-13 11:16
hehe, yes thanks!
