### ISSUE TITLE
Update the documentation on the homepage

### ISSUE THREAD

**Issue by jakjen** [ZoomerAnalytics/xlwings#906] opened 2018-06-26 12:41 UTC
I have now tried for several hours, installing xlwings in excel.
To be honest: the documentation on xlwings homepage is INSANELY bad! There is no explenation, for instance 

"While the defaults will often work out-of-the box, you can change the global settings directly in the add-in:"

where in the add-in?! 

You should really consider give the homepage a thorough re-read! After lots of hours, I simply have to find another solution.

**Comment by rhkleijn** [comment] 2018-06-26 15:39
[](http://docs.xlwings.org/en/stable/_images/ribbon.png)

**Comment by jakjen** [comment] 2018-06-27 14:38
I would not call it insulting - it is just a fact that is insanely/really/very badly documented. 
Regarding my "question", it was not a question but an example of the messy/non-existing explanation.

I do agree that the add-in is really (!) usefull when you have installed it. It took me around 8 hours, 4 youtube videos and a lot of guessing to make it work, and to call a "hello world" function.

My point was that they should really give the documentation/examples a serious read-through, because a lot of it simply does not make sense.

**Comment by Colin-b** [comment] 2018-06-27 17:38
I guess it always depends on your background. Feedback is always useful but for it to be you should come with a proposal or at least an accurate description of your issue.

For example in your case you were trying to install the xlwings add-in. Did you struggle to find the page with installation steps? Is the page missing? What change would you recommend for newcomers to have a faster understanding of the steps to follow? And so on :-)

Again feedback is often a good thing but the best way to solve an issue is often by having a sane discussion, current focus for xlwings team might not be xlwings documentation at the moment, coming up with clear and detailed steps would certainly help them :-)

**Comment by fzumstein** [comment] 2018-06-28 12:18
duplicate of https://github.com/ZoomerAnalytics/xlwings/issues/704

**Closed by fzumstein** 2018-06-28 12:18 UTC
