### ISSUE TITLE
Run-time error '1004': Cannot run the macro 'xlwings-test.xlsm!ImportPythonUDFs'. The macro may not be available in this workbook or all macros may be disabled.

### ISSUE THREAD

**Issue by EranBenHorin** [ZoomerAnalytics/xlwings#331] opened 2015-12-18 14:54 UTC
Hi,
I get this error when I do the following:
1. `xlwings template open`
2. Save as `x.xlsm` if the python file is `x.py` - whilst making sure the two files are in the same directory.

I also enabled `Trust access to the VBA project object model` as I should have.

Excel version: 15.0.4779.1001 64-bit
xlwings version 0.6.2
Win 8.1.

**Comment by fzumstein** [comment] 2015-12-18 14:58
OK so can you please download and unzip the udf sample from the homepage, and check if it runs OK (change some numbers or click the button) and then click on the import button again to see if you get the same error?

Alternatively, click `Alt - F8` and see if the ImportPythonUDFs appears in the list of macros, if yes, run it.

**Comment by EranBenHorin** [comment] 2015-12-18 15:24
It worked. Interesting..

**Comment by fzumstein** [comment] 2015-12-18 17:12
So it must have probably been an issue with the xlwings VBA module that you were using. Need to check the template if something has gone wrong there.

**Comment by fzumstein** [comment] 2015-12-19 15:11
Seems all good. I am closing this issue as I bet there was something wrong with your xlwings VBA module.

**Comment by fzumstein** [comment] 2015-12-21 14:38
In the meantime I could duplicate the issue...but haven't found the real reason yet.

**Comment by EranBenHorin** [comment] 2015-12-21 14:40
you mean replicate / reproduce the issue?

**Comment by fzumstein** [comment] 2015-12-21 14:41
yes

**Comment by fzumstein** [comment] 2015-12-21 15:21
This was caused by blanks/dashes in the filename, see also answer on StackOverflow. It is now fixed and will be available with the next release.

**Closed by fzumstein** 2015-12-21 15:21 UTC
Labels: bug
