### ISSUE TITLE
Internal error when Workbook does not exist

### ISSUE THREAD

**Issue by Juanlu001** [ZoomerAnalytics/xlwings#502] opened 2016-07-01 14:25 UTC
When trying to open a Workbook that does not exist, a `TypeError` exception with no meaningful information appears instead of an appropriate error message.

```
In [12]: xw.Workbook("TEST")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-6423f69d4cf8> in <module>()
----> 1 xw.Workbook("TEST")

c:\python27\lib\site-packages\xlwings\main.pyc in __init__(self, fullname, xl_workbook, app_visible, app_target)
    174             if not os.path.isfile(fullname) or xlplatform.is_file_open(self.fullname):
    175                 # Connect to unsaved Workbook (e.g. 'Workbook1') or to an opened Workbook
--> 176                 self.xl_app, self.xl_workbook = xlplatform.get_open_workbook(self.fullname, app_target)
    177             else:
    178                 # Open Excel and the Workbook

TypeError: 'NoneType' object is not iterable
```

https://github.com/ZoomerAnalytics/xlwings/blob/5cd9cfc/xlwings/main.py#L175

while I would expect something like a `RuntimeError` or an `IOError` informing that such Workbook does not exist or could not be opened.

cc @skasi7

**Comment by fzumstein** [comment] 2016-07-02 10:15
Duplicate of https://github.com/ZoomerAnalytics/xlwings/issues/49

**Closed by fzumstein** 2016-07-02 10:15 UTC
