### ISSUE TITLE
Issue : Retrieving " ' " starting cells numbers

### ISSUE THREAD

**Issue by Lanezriel** [ZoomerAnalytics/xlwings#1037] opened 2019-02-22 11:11 UTC
Windows Server 2012 R2 Standard
xlwings 0.13.0
Excel 2010
Python 3.7.0 (WinPythonZero)

Issue :
I have multiple Excel files that I need to change.

One of them il a ".xlsm" format and needs to be copied in a ".xlsx" format (no problem here at the moment)
** I just take every sheet and copy them in the new workbook

For the other Excel files, I need to copy them somewhere else (no problem) and update every link that were made to the previous ".xlsm" file to make them point to the ".xlsx" version of it.
ISSUE 1 : If I try to "sheet.api.UsedRange.Replace(previous_name, new_nam, 2, 1, False), it blocks in one of the sheet of a big Excel file.

==> I tried this to avoid the ISSUE 2

ISSUE 2 : If I try to get the formulas of used_range (xlwings this time) in a DataFrame, first, it gives me tuple of tuples and not a dataframe (no problem here, I get it back to a dataframe by transforming this in a list of lists and then to DataFrame), but the formulas that were read have something missing. That thing is the " ' " in the beginning of some cells.

The thing is, even if those " ' " are missing, the values are read unchanged, but when, I put these back in the sheet, the "text numbers" that were previously " 'xxxxx " are written " xxxxx " and I lose the first 0 in the front cause Excel thinks they are numbers (but I want them to stay TEXT).

I can't number_format the whole used_range cause there are some numbers that need to stay numbers, and I also got dates to deal with.

These files have various size sheets some goes "A1:G10", others go "A1:MN354" for example.

For more details, these files have values like :

* ID of things (numbers that must stay as TEXT) ==> These ones are written with a " ' " in the original file
* Values of elements of the things (numbers that must stay numbers)
* Text
* Dates
(some are from formula, some are from directly written values)

Every file is differently arranged.

So I need to get all the values and formulas to stay exactly the same, and only change the links that point to the old ".xlsm" file so they point to ".xlsx" instead.

I have no error by python or else, beacause my script works till the end.

The resulting values are then a problem.

Text like " '0356231354 " becomes " 356231354 " so everything that depend on these values will fail later.

I unfortunately can't give any Excel file as our data are not allowed outside but I guess my explanation gives you enough information to understand (and/or test) the problem.

Another important thing, I have a performance challenge on this.

There is a VBS code that does what I'm trying to do, using only Ecxel api functions and takes ~45 minutes to be done.

My version takes ~11 minutes to be done (with the working xlwings part) but gives me mistaken final values that lost the first 0.

Here is a part of my code :

```python
def generate_ref_jdd(log_sht, ref_jdd_source_path, ref_jdd_dest_path, onglet_ref_jdd):
	xl_app = xw.App(visible=False)
	xl_app.display_alerts = False
	new_wb = xl_app.books.add()
	source_wb = xl_app.books.open(ref_jdd_source_path)
	
	for source_sht in source_wb.sheets:
		if source_sht.name == onglet_ref_jdd or "c_" in source_sht.name:
			try:
				if source_sht.name == onglet_ref_jdd:
					new_sht = new_wb.sheets.add(name=source_sht.name, before="Feuil1")
					new_sht.cells.number_format = "@"
					df = source_sht.range('A1').expand().options(pd.DataFrame, index=False, header=False).value
					new_sht.range('A1').options(index=False, header=False).value = df
				elif "c_" in source_sht.name:
					new_sht = new_wb.sheets.add(name=source_sht.name, before="Feuil1")
					
					source_wb.activate()
					source_sht.activate()
					
					source_sht.api.Unprotect
					source_sht.api.AutoFilterMode = False
					source_sht.api.Range('B1').AutoFilter
					source_sht.api.Range('B1').AutoFilter(2, "*Réservée par " + onglet_ref_jdd + "*")
					
					source_sht.api.Range('A1').CurrentRegion.Select()
					xl_app.api.Selection.Copy()
					
					new_sht.api.Range('A1').PasteSpecial(12)
					xl_app.api.CutCopyMode = False
			except Exception as e:
				print(e)
				write_log(log_sht, "ERROR", "Une erreur est survenue lors du traitement de l'onglet " + source_sht.name + ". Arrêt de la génération du référentiel d'exécution.")
				xl_app.kill()
				return False
	
	source_wb.close()
	new_wb.api.SaveAs(ref_jdd_dest_path, 51)
	new_wb.close()
	xl_app.quit()
	write_log(log_sht, "INFO", "RefJDD : Traitement OK")
	
	return True
```

The above code works fine

```python
def change_jdd_link(log_sht, ref_exec_file, base_link, updated_link):
	xl_app = xw.App(visible=False)
	xl_app.display_alerts = False
	wb = xl_app.books.open(ref_exec_file)
	
	print(ref_exec_file)
	
	for sheet in wb.sheets:
		print(sheet.name)
		print("----------------------------")
		# print(sheet.range('A2').expand().address)
		print(sheet.used_range.address)
		if not "MainDetails_" in sheet.name and not "Autoreleve_" in sheet.name:
			# df = sheet.range('A2').expand().options(pd.DataFrame, index=False, header=False).formula
			
			xl_app.api.EnableEvents = False
			xl_app.api.ScreenUpdating = False
			xl_app.api.Calculation = -4135
			sheet.api.EnableCalculation = False
			sheet.used_range.api.Replace(base_link, updated_link, 2, 1, False)
			sheet.api.EnableCalculation = True
			xl_app.api.Calculation = -4105
			xl_app.api.ScreenUpdating = True
			xl_app.api.EnableEvents = True
			
			# df = sheet.used_range.options(pd.DataFrame, index=False, header=False).formula
			# df = list(df)
			# for i, line in enumerate(df):
				# df[i] = list(df[i])
			# print("Transformation en dataframe")
			# df = pd.DataFrame(df)
			# print("Remplacement des liens")
			# df.replace({base_link:updated_link}, inplace=True, regex=True)
			# print("Ecriture dans le fichier excel")
			# sheet.range('A2').options(pd.DataFrame, index=False, header=False).value = df.iloc[1:]
		print("****************************")
	
	wb.save()
	wb.close()
	xl_app.quit()
	
	return True
```

In the second function, the commented part is the one that works but gives me the wrong values in the end (I mean without the " ' "), the uncommented part just above, is the try to avoid this problem, but that keeps blocking on a big sheet, so it never finishes.

Does anyone have an idea how I could get those formulas in one shot in a Dataframe, while keeping the " ' " that are in the beginning of some of the cells, so I can get them back in the file (with the link updated) in the right format ?

It's been 3 days I'm on this but never found any issue like this or solutions on the internet.

Thank you in avance for your answers.

**Comment by fzumstein** [comment] 2019-02-22 19:31
this is a duplicate of #36, a workaround is mentioned there

**Closed by fzumstein** 2019-02-22 19:31 UTC

**Comment by Lanezriel** [comment] 2019-02-22 20:36
I've already seen that issue before creating mine.

I understand that you found a relation to this one because there is a relation about writing the data.

But there is a difference between the two.

In my problem, I can't easily just add a simple quote in front of my values because I have no real way of knowing when I need to do it.

As I told before, I have 3 types of numeric values : Text numbers, real numbers, date type numbers.

For date type numbers, I can know, of course, but for the two others, I can't realy be sure which one is supposed to be text and which is supposed to be number.

The bigger problem is that some columns have both.

In the same column, I have real numbers AND text numbers (marked with that simple quote in the cell).

In the other issue you mentionned, the problem was just to write a simple number value as string. I already know how to do that.

What I can't figure out (and need to do), is how I can read the value without losing that quote.

I was looking for a way to read the quote, so I could win time processing the changes in my data without trying to iterate trough every columns of the dataframe, trying to understand if that's a number that is supposed to be text or not.

If no one have anything to do that, then let's close this.

But if you understand the difference here, could we keep it open ?

Maybe xlwings needs an update on reading values to have real "raw values" that can keep any singe character in a cell, even if it's a charater that is just used to format a cell ?

Sorry if I'm going too far in my thinking.

But thank you for your answer that was quite fast.

**Comment by fzumstein** [comment] 2019-02-23 13:09
I think the leading `'` behaves equally difficult in VBA. If you could change the cell's number format to text, you would be able to read it `....range(...).number_format` and react accordingly.

Also, are you using something like `xw.Book("Book2").sheets[0].api.Copy(After=xw.Book("Book3").sheets[0].api)` to copy over sheets? This will preserve the formatting.

**Comment by Lanezriel** [comment] 2019-02-23 13:27
As soon as I'm back to work monday, I'll try your hint.

I'll open my book, set number_format = "@" to the full sheet, read it et then try to make my change and set it back to the file.

I just wonder if the fact that I would have changed the number format won't get me wrong when I write it back. I think maybe I should set it back to normal after reading it so I would only keep the quoted one as text (or real text too).

Also, for your question, I copy the used_range of some sheets of the first file only, using : 

``` python
new_sht = new_wb.sheets.add(name=source_sht.name, before="Feuil1")
					
source_wb.activate()
source_sht.activate()
					
source_sht.api.Unprotect
source_sht.api.AutoFilterMode = False
source_sht.api.Range('B1').AutoFilter
source_sht.api.Range('B1').AutoFilter(2, "*Réservée par " + onglet_ref_jdd + "*")
					
source_sht.api.Range('A1').CurrentRegion.Select()
xl_app.api.Selection.Copy()
					
new_sht.api.Range('A1').PasteSpecial(12)
xl_app.api.CutCopyMode = False
```

That is because for this file, I don't need the full original format.

But I'm gonna try it to see what it looks like, and see with my colleagues if our test automation can use it correctly if I try it the way you mentionned.

For all the other files, I just copy the full file to the same place as the "file.xslm" was changed to "file.xlsx" and then, I getting inside those 30+ files to update the links in every sheets by getting them in DF and using replace function to change the file extension. The, I write my sheet back where it was.

As they are Excel intelligent table (but not all of them), i have to write it back beginning by the second line so every "intelligent formula" doesn't lose the related column name.

For example, if I put back the full table, with the column name, every "[@[COLUMN_NAME]]" are lost.

So I have to write it on second line.

Even more complicated, some tables begin at line 5 or 8 (hopefuly, they are not intelligent excel table so I can replace the column name for those).

So my guess was to read the full table (telling pandas DF that there are no Index or Header), then write it back starting on second line, skipping the first row of my DF so every intelligent table can continue working.

Thank you again for your answer.

I'll keep you informed of the result.

**Comment by Lanezriel** [comment] 2019-02-25 08:47
I'm back to tell you the result of the last tests.

If I try to set number_format to the needed range to "@" so I could try to get the leading " ' " when reading it, it give me the exact same value as if nothing was done.

I'm actually trying to add an addtional leading " ' " to every formulas in the range.

It's been 10 minutes now, end it hasn't finished adding that character.

So this can't be the way to do it for me.

I'm trying to think of an other way to get it.

During the tests, I saw that the cells with a leading " ' " are considered number_format == "@" while Excel itself says "Standard" while you are viewing this info in the format shown on the Application.

I guess I could try to read every single "number_format" for the range, and force it for the cells that xlwings show as "@".

I'll tell you what it does.
