### ISSUE TITLE
conda environment can't import numpy

### ISSUE THREAD

**Issue by FalseProtagonist** [ZoomerAnalytics/xlwings#977] opened 2018-11-01 11:28 UTC
#### OS (e.g. Windows 10 or macOS Sierra)
Windows 7
#### Versions of xlwings, Excel and Python (e.g. 0.11.8, Office 365, Python 3.7)
0.11.8, Office Standard 2016, Python  3.7.0
#### Describe your issue (incl. Traceback!)

Trying to run udf_modules specifying a conda python environment gives error when importing pandas  (traceback below). I'm not certain how we're supposed to use conda environments (is it possible to specify a custom python launch command, eg. "activate environment_name; python" - doesn't work when set as interpreter)

The approach I was taking to try and make it work: set interpreter to the location of python in the environment:
"C:\Users\myname\AppData\Local\Continuum\anaconda3\envs\dataportal\pythonw.exe"

Put into PYTHONPATH what you get in sys.path when you activate the environment from command (have checked this is working by writing a UDF which outputs sys.path back to the book, which works).

Interestingly this PYTHONPATH doesn't seem to make a difference either way, with or without it the Add-In seems to be adding the conda site-packages and importing numpy fails (but importing pandas only fails when pandas tries to pull numpy).

The environment itself is fine, if I command-line activate it pandas works.

My guess is that importing numpy might be dependent on environment variables (not sys.path) and those are missing.

```python
# Your traceback here
---------------------------
Error
---------------------------
Original error was: DLL load failed: The specified module could not be found.
files not under version control).  Otherwise reinstall numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
likely you are trying to import a failed build of numpy.
Importing the multiarray numpy extension module failed.  Most
ImportError: 
    raise ImportError(msg)
  File "C:\Users\myname\AppData\Local\Continuum\anaconda3\envs\dataportal\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\myname\AppData\Local\Continuum\anaconda3\envs\dataportal\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    from .type_check import *
  File "C:\Users\myname\AppData\Local\Continuum\anaconda3\envs\dataportal\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\myname\AppData\Local\Continuum\anaconda3\envs\dataportal\lib\site-packages\numpy\add_newdocs.py", line 13, in 
---------------------------
OK   
---------------------------
```

#### Include a minimal code sample to reproduce the issue (and attach a sample workbook if required!)

```python
import numpy as np
```

**Comment by fzumstein** [comment] 2018-11-01 11:38
This is a duplicate of https://github.com/ZoomerAnalytics/xlwings/issues/954, please add further comments there, I am closing this one.

**Closed by fzumstein** 2018-11-01 11:38 UTC

**Comment by FalseProtagonist** [comment] 2018-11-01 11:43
Thanks, sorry about that I missed it searching.
