### ISSUE TITLE
Issue Reading in Dates

### ISSUE THREAD

**Issue by michaelwangWUSTL** [ZoomerAnalytics/xlwings#920] opened 2018-08-07 02:53 UTC
Can't read in values when formatted as a Date? When a column is formatted as a Date I get an error reading in the cell, but if it's formatted differently I can read in the value.

**Comment by michaelwangWUSTL** [comment] 2018-08-07 04:10
For instance, if I try to read in 
6/13/2018
it crashes.

**Comment by michaelwangWUSTL** [comment] 2018-08-07 04:30
I figured out it was a number_format issue. But how do I figure out what are the possible values I can set a cell.number_format to?

**Comment by michaelwangWUSTL** [comment] 2018-08-08 01:36
Could someone help me write a converter? The default converter can't read in the date so what base should I specify so it at least reads in the value? I believe it is reading in "6/13/2018" as a float which is overflowing the memory. 

from xlwings.conversion import Converter

class MyConverter(Converter):

    @staticmethod
    def read_value(value, options):
        myoption = options.get('myoption', default_value)
        return_value = value  # Implement your conversion here
        return return_value

    @staticmethod
    def write_value(value, options):
        myoption = options.get('myoption', default_value)
        return_value = value  # Implement your conversion here
        return return_value

**Comment by fzumstein** [comment] 2018-08-08 09:07
Can you attach or send me a sample spreadsheet that crashes?

**Comment by michaelwangWUSTL** [comment] 2018-08-08 13:29
[date_error.xlsx](https://github.com/ZoomerAnalytics/xlwings/files/2270402/date_error.xlsx)

Absolutely, thanks for your help. I've been able to get around the issue by setting the number_format to '@', but its a pretty dirty solution. I imagine a converter would be better?

**Comment by fzumstein** [comment] 2018-08-08 23:06
I can't replicated the issue with the attached spreadsheet. What language is your Excel in and can you provide the exact python command and error?

**Comment by michaelwangWUSTL** [comment] 2018-08-09 05:31
Sure. My language is English and here's the sample code. Thanks for your help!

import xlwings as xw

# OPEN ROUTE WORKBOOK AND SHEET
test_workbook = xw.Book(r'filelocation\date_error.xlsx')
test_sheet = test_workbook.sheets['Sheet1']
print(test_sheet.range('A3').value)

Process finished with exit code -1073741819 (0xC0000005)

**Comment by fzumstein** [comment] 2018-08-28 22:00
duplicate of https://github.com/ZoomerAnalytics/xlwings/issues/914

**Closed by fzumstein** 2018-08-28 22:00 UTC

**Comment by chinaniu** [comment] 2022-05-24 12:17
when i use xlwings write in excel. the yyyy-mm-dd become yyyy/mm/dd, How do I set it up so it doesn't happen
