### ISSUE TITLE
runpython EOL error vba - python

### ISSUE THREAD

**Issue by callaloma** [ZoomerAnalytics/xlwings#754] opened 2017-09-16 10:27 UTC
Hi All,

I have been looking for a solution to my problem for days and days and now I'm lost.
I've written some python code, which I would like to use for updating data in an excel sheet using the module requests.

I installed xlwings and the addon.
However, everytime I run the VBA code, I get the error:

  File "<string>", line 1

    import sys, os;sys.path.extend(os.path.normcase(os.path.expandvars('/Users/Dennis/Documents/crypto;

                                                                                                      ^

SyntaxError: EOL while scanning string literal

Does anyone know why this is happening? 

Thanks everyone.

**Comment by sdementen** [comment] 2017-09-16 10:59
I looks like the python code is truncated somewhere. The python code you've posted is missing closing quotes and closing parentheses at least...

**Comment by sdementen** [comment] 2017-09-16 11:00
Would you have a bit more context (the python file you're calling or the string you pass to runpython for instance)

**Comment by callaloma** [comment] 2017-09-16 14:28
Hi, sorry it seems like my browser has crashed the correct layout of what I intended to show.


This is my Python code:

import requests, json
from datetime import datetime
import xlwings as xw

def do():
    parameter = {'convert' : 'EUR'}

    #anfrage über API
    query_ticker = requests.get('https://api.coinmarketcap.com/v1/ticker', params = parameter)


    #anfragedaten in JSON-format
    data_ticker = query_ticker.json()


    wb = xw.Book.caller()
    ws0 = wb.sheets['holdings']

    for entry in data_ticker:

        # update eth price
        if entry['symbol'] == 'ETH':
            ws0.range('B14').value = float(entry['price_eur'])

        #update btc price
        if entry['symbol'] == 'BTC':
            ws0.range('B15').value = float(entry['price_eur'])

        if entry['symbol'] == 'NEO':
            ws0.range('B16').value = float(entry['price_eur'])

        if entry['symbol'] == 'XRP':
            ws0.range('B17').value = float(entry['price_eur'])

    now = datetime.now()
    write_date = '%s.%s.%s' %(now.day, now.month, now.year)
    write_time = '%s:%s:%s' %(now.hour, now.minute,now.second)

    ws0.range('B2').value = write_date
    ws0.range('B3').value = write_time

    #wb.save('holdings.xlsx')
    #wb.close()


This is the VBA code I call:

Sub update_holdings()
    RunPython ("import update_holdings;update_holdings.do()")
End Sub



Thanks for your help!

**Comment by callaloma** [comment] 2017-09-16 14:36
Hi, sorry it seems like my browser has crashed the correct layout of what I intended to show.

**this is my python code:**

`import requests, json
from datetime import datetime
import xlwings as xw

def do():
    parameter = {'convert' : 'EUR'}

    #anfrage über API
    query_ticker = requests.get('https://api.coinmarketcap.com/v1/ticker', params = parameter)


    #anfragedaten in JSON-format
    data_ticker = query_ticker.json()


    wb = xw.Book.caller()
    ws0 = wb.sheets['holdings']

    for entry in data_ticker:

        # update eth price
        if entry['symbol'] == 'ETH':
            ws0.range('B14').value = float(entry['price_eur'])

        #update btc price
        if entry['symbol'] == 'BTC':
            ws0.range('B15').value = float(entry['price_eur'])

        if entry['symbol'] == 'NEO':
            ws0.range('B16').value = float(entry['price_eur'])

        if entry['symbol'] == 'XRP':
            ws0.range('B17').value = float(entry['price_eur'])

    now = datetime.now()
    write_date = '%s.%s.%s' %(now.day, now.month, now.year)
    write_time = '%s:%s:%s' %(now.hour, now.minute,now.second)

    ws0.range('B2').value = write_date
    ws0.range('B3').value = write_time

    #wb.save('holdings.xlsx')
    #wb.close()
`


Thanks in advance!


**this is the vba code:**

`Sub update_holdings()
    RunPython ("import update_holdings;update_holdings.do()")
End Sub`

**Comment by callaloma** [comment] 2017-09-16 14:42
Hi, thanks for the fast answer. Sorry for the layout, seems like my safari has crashed the way I actually wanted it to be shown.


**This is the python code:**

`Import requests, json
from datetime import datetime
import xlwings as xw

def do():
    parameter = {'convert' : 'EUR'}

    #anfrage über API
    query_ticker = requests.get('https://api.coinmarketcap.com/v1/ticker', params = parameter)


    #anfragedaten in JSON-format
    data_ticker = query_ticker.json()


    wb = xw.Book.caller()
    ws0 = wb.sheets['holdings']

    for entry in data_ticker:

        # update eth price
        if entry['symbol'] == 'ETH':
            ws0.range('B14').value = float(entry['price_eur'])

        #update btc price
        if entry['symbol'] == 'BTC':
            ws0.range('B15').value = float(entry['price_eur'])

        if entry['symbol'] == 'NEO':
            ws0.range('B16').value = float(entry['price_eur'])

        if entry['symbol'] == 'XRP':
            ws0.range('B17').value = float(entry['price_eur'])

    now = datetime.now()
    write_date = '%s.%s.%s' %(now.day, now.month, now.year)
    write_time = '%s:%s:%s' %(now.hour, now.minute,now.second)

    ws0.range('B2').value = write_date
    ws0.range('B3').value = write_time

    wb.save('holdings.xlsx')
    #wb.close()`

**this is the vba code:**

`Sub update_holdings()

    RunPython ("import update_holdings;update_holdings.do()")

End Sub`


Thanks for you help!

**Comment by fzumstein** [comment] 2017-09-16 18:43
Which version of Mac Excel are you using?

**Comment by callaloma** [comment] 2017-09-16 20:00
Excel 2016 for Mac

**Comment by callaloma** [comment] 2017-09-17 13:54
I have just downloaded the xlwings fibonacci example, and it throws the exact same error..

**Comment by fzumstein** [comment] 2017-09-17 20:13
Can you paste your user settings (screenshot from either the addin or the config sheet)? specifically the PYTHONPATH

**Comment by callaloma** [comment] 2017-09-17 22:05
/Users/Dennis/Desktop/Bildschirmfoto 2017-09-17 um 23.56.47.png


Thanks for your help.. I am really in trouble here..

**Comment by callaloma** [comment] 2017-09-17 22:06
Thanks for the help.. I am really in trouble here.

**Comment by callaloma** [comment] 2017-09-18 09:59
Hi fmzumstein,

your approach helped me solve this issue:




I went to check my xlwings.conf file, in order to see the setup for "INTERPRETER" and "PYTHONPATH". I never did editing on this, however, it was formatted incorrectly.

My config file was setup this way:

    "PYTHONPATH","
    "
    "INTERPRETER","Python"

Do you have an idea how this could have happended? 

Also, the path to my python was set incorrectly by default. Even though my command line works with Anaconda python 3.6, "pythonw" used the Interpreter set in .bash_profile referenced to python 2.7 which came pre-installed with macOS.
Editing the config file "INTERPRETER" solved this issue.

Thanks everyone.

**Comment by fzumstein** [comment] 2017-09-18 20:31
the default behaviour of .bash_profile is by design: http://docs.xlwings.org/en/stable/addin.html?highlight=bash_profile#global-settings

the config file I don't know, somewhere along the way it got mixed . might be a bug or you entered something that it didn't liked in the addin...I am closing this issue, if you see the config file mixup coming back, feel free to reopen.

**Closed by fzumstein** 2017-09-18 20:31 UTC
