### ISSUE TITLE
Google Analytics Example: AttributeError: 'module' object has no attribute 'run'

### ISSUE THREAD

**Issue by bevinahally** [ZoomerAnalytics/xlwings#309] opened 2015-11-26 00:27 UTC
Hi, 

First of all, I find your product absolutely fascinating and it's a great way to get developers and finance professionals to work together.

I was trying to use the Python-Excel integration for Google Analytics using the steps mentioned here. 
http://blog.zoomeranalytics.com/google-analytics/

I wanted to know if you'd be able to point out why I get this following error when I place the JSON in the correct extracted folder and enter the correct Account, Property and View information. Any idea why this happens? A friend of mine encountered the same trouble as well.

---------------------------
Error
---------------------------
Traceback (most recent call last): 
  File "<string>", line 1, in <module> 
  File "C:\Python27\ga_dashboard.py", line 80, in refresh 
    behavior(start_date, end_date, account_name, property_name, profile_name, max_results) 
  File "C:\Python27\ga_dashboard.py", line 36, in behavior 
    chunksize=10000) 
  File "C:\Users\John Smith\Anaconda\lib\site-packages\pandas\io\ga.py", line 104, in read_ga 
    reader = GAnalytics(**reader_kwds) 
  File "C:\Users\John Smith\Anaconda\lib\site-packages\pandas\io\ga.py", line 173, in __init__ 
    self._service = self._init_service(secrets) 
  File "C:\Users\John Smith\Anaconda\lib\site-packages\pandas\io\ga.py", line 185, in _init_service 
    http = self.authenticate(secrets) 
  File "C:\Users\John Smith\Anaconda\lib\site-packages\pandas\io\ga.py", line 145, in authenticate 
    return auth.authenticate(flow, self.token_store) 
  File "C:\Users\John Smith\Anaconda\lib\site-packages\pandas\io\auth.py", line 108, in authenticate 
    credentials = tools.run(flow, storage) 
AttributeError: 'module' object has no attribute 'run' 
 
Press Ctrl+C to copy this message to the clipboard.
---------------------------
OK   
---------------------------

**Comment by fzumstein** [comment] 2015-11-26 08:16
the google analytics module in pandas has been unmaintained and will be removed from pandas: http://stackoverflow.com/questions/32802232/cannot-get-python-pandas-google-analytics-connection-to-work

I will be working on a fix for this - in the meantime I ll post a comment on the homepage

**Comment by fzumstein** [comment] 2015-11-26 09:31
OK so the error is caused by `oauth2client`, if you downgrade to version `1.4.12`, it will give you the deprecation warning but will again work for now. However, it's only a matter of time until this breaks again, so I will still have to update the example to move away from the built-in pandas ga module.

**Comment by fzumstein** [comment] 2015-11-26 12:57
See also: https://github.com/pydata/pandas/issues/11308

**Comment by fzumstein** [comment] 2015-11-26 15:10
I have now added a conda environment files (recommended) and a pip requirements.txt. 

In the future we might reimplement the query with something like https://github.com/panalysis/Google2Pandas

**Comment by bevinahally** [comment] 2015-11-26 20:58
Felix, that fixed the problem. This can be a very useful tool moving forward, I look forward to using this more! 

Regards

**Closed** 2016-01-22 10:37 UTC
Labels: bug
