### ISSUE TITLE
Unable to save excel file as '.xlsm'

### ISSUE THREAD

**Issue by ant10484** [ZoomerAnalytics/xlwings#796] opened 2018-01-07 16:44 UTC
Hi,
I am unable to save a workbook as an xlsm file. I tried the code below:

```
>>> import xlwings
>>> xlwings.Book()
<Book [Book1]>
>>> xlwings.Book().save('test.xlsm')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\xlwings\main.py", line 688, in save
    return self.impl.save(path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 483, in save
    self.xl.SaveAs(os.path.realpath(path))
  File "C:\ProgramData\Anaconda3\lib\site-packages\xlwings\_xlwindows.py", line 63, in __call__
    v = self.__method(*args, **kwargs)
  File "<COMObject Add>", line 7, in SaveAs
pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft Excel', 'This extension can not be used with the selected file type. Change the file extension in the File name text box or select a different file type by changing the Save as type.', 'xlmain11.chm', 0, -2146827284), None)
```

I am unable to find any documentation on this, just the one query in which the method 'Workbook()' is used. I don't know what I am missing here. Kindly help. 
Thanks

**Comment by fzumstein** [comment] 2018-01-07 17:11
this is a duplicate of #187. I'll see if I can get this in for next release.

**Closed by fzumstein** 2018-01-07 17:11 UTC
