### ISSUE TITLE
Refactoring VBA Code for UDF

### ISSUE THREAD

**Issue by arita291** [ZoomerAnalytics/xlwings#375] opened 2016-02-29 20:44 UTC
Hi,

As mentionned, VBA code generated by UDF is "very verbose":
especially for input conversion (VBA type to Python type), there is IF sections.

Is there a way to reduce the amount of VBA code by factoring the conversion (IF THEN) type ?

Less VBA code, will be more stable Excel (thinking of 300 UDF functions...).
Something like this : 

'Function matrix_mult(x, y)
       name1 = "matrix_mult"
      ' If TypeOf Application.Caller Is Range Then On Error GoTo failed

        x = convert(x, "numpyarray")
        y = convert(y, "numpyarray")
       Set args = Py.Tuple(x, y)       'set the argument
       matrix_mult = callpython(name1, func, args)
       Exit Function

end Function

**Comment by fzumstein** [comment] 2016-02-29 21:24
Duplicate of #370. Please don't open 2 issues for the same things. The new version v0.7 will be released soon and take care of this.

**Closed by fzumstein** 2016-02-29 21:24 UTC
