### ISSUE TITLE
Propose a more specific Exception for invalid xw.Book.caller() calls.

### ISSUE THREAD

**Issue by Kamforka** [ZoomerAnalytics/xlwings#859] opened 2018-05-04 10:45 UTC
Hey guys,

The past few days I was doing some look around in the `xlwings` module and when I tried to set up a `try - except` block to catch an exception for a call to `Book.caller()` with the caller being unset I realized that the the exception is being kinda broad, so I guess a more specific one should be used instead.

Current behavior:

```python
import xlwings as xw
>>> xw.Book.caller()
Traceback (most recent call last):
  File "<pyshell#46>", line 1, in <module>
    xw.Book.caller()
  File "C:\...\Python\Python36\lib\site-packages\xlwings\main.py", line 554, in caller
    raise Exception('Workbook.caller() must not be called directly. Call through Excel or set a mock caller '
Exception: Workbook.caller() must not be called directly. Call through Excel or set a mock caller first with Book.set_mock_caller().
```

As for now a plain `Exception` is being raised for the invalid call.

My proposal would be to change it to something like: `CallerError` or `CallerException` or anything else that is meaningful here.

Regards,
Kamfor

**Comment by fzumstein** [comment] 2018-05-04 12:07
This is kind of a duplicate of https://github.com/ZoomerAnalytics/xlwings/issues/322, the issue is also logged on the roadmap, see: https://github.com/ZoomerAnalytics/xlwings/issues/324 so I am closing this.

**Closed by fzumstein** 2018-05-04 12:07 UTC
