### ISSUE TITLE
"Import functions" fails with "Could not activate Python COM server, hr = -2147023541"

### ISSUE THREAD

**Issue by bjrnfrdnnd** [ZoomerAnalytics/xlwings#766] opened 2017-10-14 15:47 UTC
This refers to issue #764.

I got xlwings to work after installing python32 and pointing the interpreters to this 32 bit installation of python (Anaconda, user installation, no admin rights)

xlwings worked then for a week.
Now it stopped working with the same error as in issue #764.
I uninstalled my Anaconda pythons (32 and 64 bit) and reinstalled only the python32 version. No change.
This time, the problem is even weirder: I can run in debug mode and from the commandline (or pycharm) - no problem, everything works.
The only thing which does not work - and the only thing of importance for a production module - is when I switch from debug mode to no-debug mode. Then, when I hit the "import functions" button of the xlwings ribbon, the error message pops up. When not hitting this button, the error message displays in a cell when running a udf.

I again traced this back to the call to my local python installation:
The last unsuccessful call was in function Py() in xlwings.xlam Main module. Line:
    `If 0 <> XLPyDLLActivateAuto(Py, XLPyCommand, 1) Then Err.Raise 1000, Description:=Py`
Py() was called from sub ImportPythonUDFs() in xlwings.xlam Main Module, line
	`tempPath = Py.Str(Py.Call(Py.Module("xlwings"), "import_udfs", Py.Tuple(GetUdfModules, ActiveWorkbook)))`

which was called from Sub ImportFunctions(control As IRibbonControl) in xlwings.xlam Main Module, line
	`ImportPythonUDFs`

The variable XLPyCommand
is
```
c:\local\Anaconda3_32\pythonw.exe -B -c "import sys, os;sys.path.extend(os.path.normcase(os.path.expandvars(r'C:\local\df\df;')).split(';'));import xlwings.server; xlwings.server.serve('$(CLSID)')"
```
(no line breaks in the actual variable)

But, actually, the program never executes the call to python (I checked by changing the string and writing to a file).

I am completely at a loss here. 
What can I do?

**Comment by bjrnfrdnnd** [comment] 2017-10-16 08:44
Update on this issue: The error has gone away again. I can import functions in no-debug mode. I have not the slightest idea what might have changed. I did not change anything between the point in time where it did not work (two days ago) and today.
Should I leave this issue open?

**Comment by fzumstein** [comment] 2017-10-20 06:54
Just to clarify: the issue has nothing to do with 32 vs 64 bit. xlwings can cope with all combinations of bitness between OS, Excel and Python as it runs out of process.
"Something" seems to be going on on your system. It's hard to judge what it would be, but if it comes back, maybe a reinstallation/repairing of MS Office would help. I am closing the issue for now, feel free to reopen later if you need to.

**Closed by fzumstein** 2017-10-20 06:54 UTC

**Comment by Damrio** [comment] 2018-10-22 08:21
Morning,
First of all, since this is my first comment on this project : warm thanks to the team and contributors as I am a very happy user of this library :)

This post is the closest from what I currently experience (e.g. erratic functioning of UDF functions) so I thought I would add my comment to it even if closed.

I currently have the following issue:
- I was using XLwings functions for over a year, without issues. 
- However since last week I got an error when running UDF functions or pressing the "Import Function" button of the add-in, and since then am not able anymore to use UDF functions. Error message is the following:

![issue_udf](https://user-images.githubusercontent.com/3134894/47283401-35162d00-d5db-11e8-9b18-66ffd48dd655.jpg)


Note that:
- Currently I still have Runpython() functions running properly
- Excel settings (e.g. Macro Trust center and reference) are in principle correct ; I have checked them again since I have the issue.


My configuration is the following:
- Windows 10, Excel 2016
- Winpython (using Python3.6), in which I upgraded XLwings to its latest version (12.1)

The only things from that configuration that recently changed are:
- an Excel security update
- I upgraded XLwings to its latest version once I saw I was having issues

Note that I did download the udf.xlsm example from the Xlwings website. This example did not work (same error as the picture above), except (very weirdly) for a brief amount of time (I have no idea why, and when I rebooted my laptop it started to misfunction again). The Fibonnacci example does work without issues. So I guess the issue is really coming from the UDF functions.

Further investigations have led me to notice:
- that the macro was having issues at the same stage as mentioned in the post above (e.g. at code line: If 0 <> XLPyDLLActivateAuto(Py, XLPyCommand, 1) Then Err.Raise 1000, Description:=Py)
- The Loadlibrary function seems to be the reason of this failure
- I have tried to run the command displayed in the error message above, in an independent console. When doing this, the code actually works and the xlwings server is started...

Any help appreciated.
Kind thanks.

**Comment by Damrio** [comment] 2018-10-30 16:03
Afternoon,
Just to mention that, like @bjrnfrdnnd, I finally was able to recover to a normal operating mode.

This [article](https://support.microsoft.com/en-us/help/812486/event-id-7000-and-1-is-not-a-valid-win32-application-error-message-whe) suggested that spaces in the Python path might generate issues, so I moved my Winpython folder to the root of my laptop (e.g. C:/winpython/...). This was enough to do the trick.

**Comment by fzumstein** [comment] 2018-10-30 16:14
thanks for feedback and link! I'll open a separate issue to investigate spaces in the python path.

**Comment by dziczekwedrowniczek** [comment] 2019-08-29 13:13
same issue. Don't have any spaces in python interpreter. any ideas?

**Comment by fzumstein** [comment] 2019-08-29 13:16
@dziczekwedrowniczek can you please open a new issue and paste your Traceback.

**Comment by fzumstein** [comment] 2021-03-07 21:32
thanks @talalvas for bumping this, I'see if I can push #974 sometime soon

**Comment by HKubinhetz** [comment] 2024-10-15 21:22
Deleting the xlwings.conf file and running the quickstart seemed to do the trick here!

**Comment by BitBytes321** [comment] 2025-01-27 21:10
I saw this same issue and it happened after my Path got modified such that I was no longer effectively using the python exe in my Conda env that had xlwings installed
